//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveYourMoneyMVC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveYourMoneyMVC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a member?.
        /// </summary>
        public static string Account_AlreadyMember_En {
            get {
                return ResourceManager.GetString("Account_AlreadyMember_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya eres miembro?.
        /// </summary>
        public static string Account_AlreadyMember_Es {
            get {
                return ResourceManager.GetString("Account_AlreadyMember_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Account_Email_En {
            get {
                return ResourceManager.GetString("Account_Email_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Account_Email_Es {
            get {
                return ResourceManager.GetString("Account_Email_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Account_Language_En {
            get {
                return ResourceManager.GetString("Account_Language_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Account_Language_Es {
            get {
                return ResourceManager.GetString("Account_Language_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login here!.
        /// </summary>
        public static string Account_LoginHere_En {
            get {
                return ResourceManager.GetString("Account_LoginHere_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Inicia sesión aquí!.
        /// </summary>
        public static string Account_LoginHere_Es {
            get {
                return ResourceManager.GetString("Account_LoginHere_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Account_Name_En {
            get {
                return ResourceManager.GetString("Account_Name_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Account_Name_Es {
            get {
                return ResourceManager.GetString("Account_Name_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a member yet?.
        /// </summary>
        public static string Account_NotMember_En {
            get {
                return ResourceManager.GetString("Account_NotMember_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Todavía no eres miembro?.
        /// </summary>
        public static string Account_NotMember_Es {
            get {
                return ResourceManager.GetString("Account_NotMember_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Account_Password_En {
            get {
                return ResourceManager.GetString("Account_Password_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Account_Password_Es {
            get {
                return ResourceManager.GetString("Account_Password_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Account_Register_En {
            get {
                return ResourceManager.GetString("Account_Register_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string Account_Register_Es {
            get {
                return ResourceManager.GetString("Account_Register_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember session?.
        /// </summary>
        public static string Account_Remember_En {
            get {
                return ResourceManager.GetString("Account_Remember_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Recordar sesión?.
        /// </summary>
        public static string Account_Remember_Es {
            get {
                return ResourceManager.GetString("Account_Remember_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir contraseña.
        /// </summary>
        public static string Account_RepeatedPassword_En {
            get {
                return ResourceManager.GetString("Account_RepeatedPassword_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string Account_RepeatedPassword_Es {
            get {
                return ResourceManager.GetString("Account_RepeatedPassword_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Log in to access to.
        /// </summary>
        public static string Account_WelcomeLogin_En {
            get {
                return ResourceManager.GetString("Account_WelcomeLogin_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido! Inicia sesión para acceder a.
        /// </summary>
        public static string Account_WelcomeLogin_Es {
            get {
                return ResourceManager.GetString("Account_WelcomeLogin_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Register here to access to.
        /// </summary>
        public static string Account_WelcomeRegister_En {
            get {
                return ResourceManager.GetString("Account_WelcomeRegister_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido! Registrate aquí para acceder a.
        /// </summary>
        public static string Account_WelcomeRegister_Es {
            get {
                return ResourceManager.GetString("Account_WelcomeRegister_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to show.
        /// </summary>
        public static string Analysis_NoData_En {
            get {
                return ResourceManager.GetString("Analysis_NoData_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO EXISTEN GASTOS QUE MOSTRAR.
        /// </summary>
        public static string Analysis_NoData_Es {
            get {
                return ResourceManager.GetString("Analysis_NoData_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expends analysis.
        /// </summary>
        public static string AnalysisTitle_En {
            get {
                return ResourceManager.GetString("AnalysisTitle_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis de gastos.
        /// </summary>
        public static string AnalysisTitle_Es {
            get {
                return ResourceManager.GetString("AnalysisTitle_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel_En {
            get {
                return ResourceManager.GetString("Button_Cancel_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Button_Cancel_Es {
            get {
                return ResourceManager.GetString("Button_Cancel_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string Button_Clean_En {
            get {
                return ResourceManager.GetString("Button_Clean_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string Button_Clean_Es {
            get {
                return ResourceManager.GetString("Button_Clean_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close_En {
            get {
                return ResourceManager.GetString("Button_Close_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Button_Close_Es {
            get {
                return ResourceManager.GetString("Button_Close_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Button_Continue_En {
            get {
                return ResourceManager.GetString("Button_Continue_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string Button_Continue_Es {
            get {
                return ResourceManager.GetString("Button_Continue_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Button_Filter_En {
            get {
                return ResourceManager.GetString("Button_Filter_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        public static string Button_Filter_Es {
            get {
                return ResourceManager.GetString("Button_Filter_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save_En {
            get {
                return ResourceManager.GetString("Button_Save_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Button_Save_Es {
            get {
                return ResourceManager.GetString("Button_Save_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search_En {
            get {
                return ResourceManager.GetString("Button_Search_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Button_Search_Es {
            get {
                return ResourceManager.GetString("Button_Search_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New expend.
        /// </summary>
        public static string CreateExpends_En {
            get {
                return ResourceManager.GetString("CreateExpends_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo gasto.
        /// </summary>
        public static string CreateExpends_Es {
            get {
                return ResourceManager.GetString("CreateExpends_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete expend.
        /// </summary>
        public static string Expends_Delete_Expend_En {
            get {
                return ResourceManager.GetString("Expends_Delete_Expend_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar gasto.
        /// </summary>
        public static string Expends_Delete_Expend_Es {
            get {
                return ResourceManager.GetString("Expends_Delete_Expend_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expend deleted successfully.
        /// </summary>
        public static string Expends_DeleteExpend_En {
            get {
                return ResourceManager.GetString("Expends_DeleteExpend_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto eliminado con éxito.
        /// </summary>
        public static string Expends_DeleteExpend_Es {
            get {
                return ResourceManager.GetString("Expends_DeleteExpend_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download CSV.
        /// </summary>
        public static string Expends_DownloadCSV_En {
            get {
                return ResourceManager.GetString("Expends_DownloadCSV_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar CSV.
        /// </summary>
        public static string Expends_DownloadCSV_Es {
            get {
                return ResourceManager.GetString("Expends_DownloadCSV_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download attached file.
        /// </summary>
        public static string Expends_DownloadFile_Expend_En {
            get {
                return ResourceManager.GetString("Expends_DownloadFile_Expend_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar fichero adjunto.
        /// </summary>
        public static string Expends_DownloadFile_Expend_Es {
            get {
                return ResourceManager.GetString("Expends_DownloadFile_Expend_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit expend.
        /// </summary>
        public static string Expends_Edit_Expend_En {
            get {
                return ResourceManager.GetString("Expends_Edit_Expend_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar gasto.
        /// </summary>
        public static string Expends_Edit_Expend_Es {
            get {
                return ResourceManager.GetString("Expends_Edit_Expend_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expend successfully edited.
        /// </summary>
        public static string Expends_EditedExpend_En {
            get {
                return ResourceManager.GetString("Expends_EditedExpend_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto modificado con éxito.
        /// </summary>
        public static string Expends_EditedExpend_Es {
            get {
                return ResourceManager.GetString("Expends_EditedExpend_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New expend successfully created.
        /// </summary>
        public static string Expends_NewExpend_En {
            get {
                return ResourceManager.GetString("Expends_NewExpend_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo gasto creado con éxito.
        /// </summary>
        public static string Expends_NewExpend_Es {
            get {
                return ResourceManager.GetString("Expends_NewExpend_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been successfully downloaded to your download directory.
        /// </summary>
        public static string Expends_PopupMessage_En {
            get {
                return ResourceManager.GetString("Expends_PopupMessage_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero se ha descargado exitosamente en tu directorio de descargas.
        /// </summary>
        public static string Expends_PopupMessage_Es {
            get {
                return ResourceManager.GetString("Expends_PopupMessage_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string Expends_Table_Created_En {
            get {
                return ResourceManager.GetString("Expends_Table_Created_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de creación.
        /// </summary>
        public static string Expends_Table_Created_Es {
            get {
                return ResourceManager.GetString("Expends_Table_Created_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expend description.
        /// </summary>
        public static string Expends_Table_Description_En {
            get {
                return ResourceManager.GetString("Expends_Table_Description_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del gasto.
        /// </summary>
        public static string Expends_Table_Description_Es {
            get {
                return ResourceManager.GetString("Expends_Table_Description_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached file.
        /// </summary>
        public static string Expends_Table_File_En {
            get {
                return ResourceManager.GetString("Expends_Table_File_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichero adjunto.
        /// </summary>
        public static string Expends_Table_File_Es {
            get {
                return ResourceManager.GetString("Expends_Table_File_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attached file.
        /// </summary>
        public static string Expends_Table_NoFile_En {
            get {
                return ResourceManager.GetString("Expends_Table_NoFile_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay fichero adjunto.
        /// </summary>
        public static string Expends_Table_NoFile_Es {
            get {
                return ResourceManager.GetString("Expends_Table_NoFile_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Expends_Table_Quantity_En {
            get {
                return ResourceManager.GetString("Expends_Table_Quantity_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Expends_Table_Quantity_Es {
            get {
                return ResourceManager.GetString("Expends_Table_Quantity_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expend type.
        /// </summary>
        public static string Expends_Table_Type_En {
            get {
                return ResourceManager.GetString("Expends_Table_Type_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de gasto.
        /// </summary>
        public static string Expends_Table_Type_Es {
            get {
                return ResourceManager.GetString("Expends_Table_Type_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show full description.
        /// </summary>
        public static string Expends_ViewComment_Expend_En {
            get {
                return ResourceManager.GetString("Expends_ViewComment_Expend_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver descripción completa.
        /// </summary>
        public static string Expends_ViewComment_Expend_Es {
            get {
                return ResourceManager.GetString("Expends_ViewComment_Expend_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string Filter_EndDate_En {
            get {
                return ResourceManager.GetString("Filter_EndDate_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de fin.
        /// </summary>
        public static string Filter_EndDate_Es {
            get {
                return ResourceManager.GetString("Filter_EndDate_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial date.
        /// </summary>
        public static string Filter_InitialDate_En {
            get {
                return ResourceManager.GetString("Filter_InitialDate_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de inicio.
        /// </summary>
        public static string Filter_InitialDate_Es {
            get {
                return ResourceManager.GetString("Filter_InitialDate_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Filter_Options_All_En {
            get {
                return ResourceManager.GetString("Filter_Options_All_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Filter_Options_All_Es {
            get {
                return ResourceManager.GetString("Filter_Options_All_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expend type.
        /// </summary>
        public static string Filter_Type_En {
            get {
                return ResourceManager.GetString("Filter_Type_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de gasto.
        /// </summary>
        public static string Filter_Type_Es {
            get {
                return ResourceManager.GetString("Filter_Type_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string InternalServerError_En {
            get {
                return ResourceManager.GetString("InternalServerError_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error del servidor.
        /// </summary>
        public static string InternalServerError_Es {
            get {
                return ResourceManager.GetString("InternalServerError_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action could not be completed due to an internal system error. Please try again..
        /// </summary>
        public static string InternalServerError_Message_En {
            get {
                return ResourceManager.GetString("InternalServerError_Message_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido completar la acción por un error interno del sistema. Vuelva a intentarlo..
        /// </summary>
        public static string InternalServerError_Message_Es {
            get {
                return ResourceManager.GetString("InternalServerError_Message_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string InvalidPassword_En {
            get {
                return ResourceManager.GetString("InvalidPassword_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales invalidas.
        /// </summary>
        public static string InvalidPassword_Es {
            get {
                return ResourceManager.GetString("InvalidPassword_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials entered are not valid.
        /// </summary>
        public static string InvalidPassword_Message_En {
            get {
                return ResourceManager.GetString("InvalidPassword_Message_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las credenciales introducidas no son validas.
        /// </summary>
        public static string InvalidPassword_Message_Es {
            get {
                return ResourceManager.GetString("InvalidPassword_Message_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string NavMenu_Analysis_En {
            get {
                return ResourceManager.GetString("NavMenu_Analysis_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis.
        /// </summary>
        public static string NavMenu_Analysis_Es {
            get {
                return ResourceManager.GetString("NavMenu_Analysis_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will log you out to ensure changes. Continue?.
        /// </summary>
        public static string NavMenu_ChangeLang_Message_En {
            get {
                return ResourceManager.GetString("NavMenu_ChangeLang_Message_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta acción cerrará la sesión para asegurar los cambios. ¿Continuar?.
        /// </summary>
        public static string NavMenu_ChangeLang_Message_Es {
            get {
                return ResourceManager.GetString("NavMenu_ChangeLang_Message_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string NavMenu_ChangeLang_Title_En {
            get {
                return ResourceManager.GetString("NavMenu_ChangeLang_Title_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar idioma.
        /// </summary>
        public static string NavMenu_ChangeLang_Title_Es {
            get {
                return ResourceManager.GetString("NavMenu_ChangeLang_Title_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string NavMenu_Create_En {
            get {
                return ResourceManager.GetString("NavMenu_Create_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string NavMenu_Create_Es {
            get {
                return ResourceManager.GetString("NavMenu_Create_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string NavMenu_DeleteAccount_En {
            get {
                return ResourceManager.GetString("NavMenu_DeleteAccount_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar cuenta.
        /// </summary>
        public static string NavMenu_DeleteAccount_Es {
            get {
                return ResourceManager.GetString("NavMenu_DeleteAccount_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expends.
        /// </summary>
        public static string NavMenu_Expends_En {
            get {
                return ResourceManager.GetString("NavMenu_Expends_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastos.
        /// </summary>
        public static string NavMenu_Expends_Es {
            get {
                return ResourceManager.GetString("NavMenu_Expends_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string NavMenu_Logout_En {
            get {
                return ResourceManager.GetString("NavMenu_Logout_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string NavMenu_Logout_Es {
            get {
                return ResourceManager.GetString("NavMenu_Logout_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis panel.
        /// </summary>
        public static string NavMenu_Panel_En {
            get {
                return ResourceManager.GetString("NavMenu_Panel_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel de análisis.
        /// </summary>
        public static string NavMenu_Panel_Es {
            get {
                return ResourceManager.GetString("NavMenu_Panel_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string NavMenu_User_En {
            get {
                return ResourceManager.GetString("NavMenu_User_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string NavMenu_User_Es {
            get {
                return ResourceManager.GetString("NavMenu_User_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string NavMenu_View_En {
            get {
                return ResourceManager.GetString("NavMenu_View_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string NavMenu_View_Es {
            get {
                return ResourceManager.GetString("NavMenu_View_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated email.
        /// </summary>
        public static string RepeatedEmail_En {
            get {
                return ResourceManager.GetString("RepeatedEmail_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email duplicado.
        /// </summary>
        public static string RepeatedEmail_Es {
            get {
                return ResourceManager.GetString("RepeatedEmail_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have not been able to create an account with the entered email, as there is one with this email address.
        /// </summary>
        public static string RepeatedEmail_Message_En {
            get {
                return ResourceManager.GetString("RepeatedEmail_Message_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hemos podido crear una cuenta con el email introducido, ya que existe una con ese email.
        /// </summary>
        public static string RepeatedEmail_Message_Es {
            get {
                return ResourceManager.GetString("RepeatedEmail_Message_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated username.
        /// </summary>
        public static string RepeatedUsername_En {
            get {
                return ResourceManager.GetString("RepeatedUsername_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario duplicado.
        /// </summary>
        public static string RepeatedUsername_Es {
            get {
                return ResourceManager.GetString("RepeatedUsername_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have not been able to create an account with the entered username, as there is one with that username.
        /// </summary>
        public static string RepeatedUsername_Message_En {
            get {
                return ResourceManager.GetString("RepeatedUsername_Message_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hemos podido crear una cuenta con el nombre de usuario introducido, ya que existe una con ese nombre.
        /// </summary>
        public static string RepeatedUsername_Message_Es {
            get {
                return ResourceManager.GetString("RepeatedUsername_Message_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registered email.
        /// </summary>
        public static string UserNotFound_En {
            get {
                return ResourceManager.GetString("UserNotFound_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email no registrado.
        /// </summary>
        public static string UserNotFound_Es {
            get {
                return ResourceManager.GetString("UserNotFound_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user registered with the provided email.
        /// </summary>
        public static string UserNotFound_Message_En {
            get {
                return ResourceManager.GetString("UserNotFound_Message_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún usuario registrado con el correo electrónico proporcionado.
        /// </summary>
        public static string UserNotFound_Message_Es {
            get {
                return ResourceManager.GetString("UserNotFound_Message_Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My expends.
        /// </summary>
        public static string ViewExpends_En {
            get {
                return ResourceManager.GetString("ViewExpends_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis gastos.
        /// </summary>
        public static string ViewExpends_Es {
            get {
                return ResourceManager.GetString("ViewExpends_Es", resourceCulture);
            }
        }
    }
}
